site_name: Ember Django Adapter
repo_url: https://github.com/dustinfarris/ember-django-adapter
pages:
  - ['index.md', 'Introduction']
  - ['configuring.md']
  - ['extending.md']
  - ['trailing-slashes.md']
  - ['embedded-records.md']
  - ['pagination.md']
  - ['coalesce-find-requests.md']
  - ['contributing.md']
  - ['changelog.md']
theme: readthedocs
google_analytics: ['UA-13275015-13', 'auto']
