site_name: Ember Django Adapter
repo_url: https://github.com/dustinfarris/ember-django-adapter
pages:
  - ['index.md', 'Introduction']
  - ['configuring.md']
  - ['extending.md']
  - ['usage.md']
  - ['pagination.md']
  - ['contributing.md']
  - ['changelog.md']
theme: readthedocs
